-- Migration: Add source document tracking to journal_entries
-- This enables automatic journal entry generation from expenses and receipts

-- Add source document tracking columns
ALTER TABLE journal_entries
ADD COLUMN IF NOT EXISTS source_document_type VARCHAR(50) NULL,
ADD COLUMN IF NOT EXISTS source_document_id UUID NULL,
ADD COLUMN IF NOT EXISTS is_auto_generated BOOLEAN DEFAULT FALSE;

-- Add comment for documentation
COMMENT ON COLUMN journal_entries.source_document_type IS 'Type of source document: expense, expense_payment, or receipt';
COMMENT ON COLUMN journal_entries.source_document_id IS 'UUID of the source document that triggered this journal entry';
COMMENT ON COLUMN journal_entries.is_auto_generated IS 'Whether this entry was automatically generated by the system';

-- Create index for efficient lookups by source document
CREATE INDEX IF NOT EXISTS idx_journal_entries_source
ON journal_entries(source_document_type, source_document_id)
WHERE source_document_type IS NOT NULL;

-- Create index for filtering auto-generated entries
CREATE INDEX IF NOT EXISTS idx_journal_entries_auto_generated
ON journal_entries(is_auto_generated)
WHERE is_auto_generated = TRUE;
